[mypy]
python_version = 3.10
strict = True
warn_unreachable = True
files = src/dfd

[mypy-cv2.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True
